name: statemachine
version: 0.0.2+m4
author: Lukas Renggli <renggli@gmail.com>
description: A simple, but generic state machine framework for Dart.
homepage: https://github.com/renggli/StateMachineDart
dev_dependencies:
  junitconfiguration: any
  unittest: '>=0.4.0'
  browser: '>=0.4.0'

#dependencies:
#  js: any
#  unittest: any