name: statemachine
version: 0.0.5
author: Lukas Renggli <renggli@gmail.com>
description: A simple, but generic state machine framework for Dart.
homepage: https://github.com/renggli/StateMachineDart
dev_dependencies:
  junitconfiguration: '>=0.5.0'
  unittest: '>=0.5.0'
  browser: '>=0.5.0'
