name: statemachine
author: Lukas Renggli <renggli@gmail.com>
version: 1.1.1
homepage: https://github.com/renggli/dart-statemachine
description: A simple, but generic state machine framework for Dart.
environment:
  sdk: '>=1.8.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.1 <0.13.0'
