name: statemachine
author: Lukas Renggli <renggli@gmail.com>
version: 1.2.1
homepage: https://github.com/renggli/dart-statemachine
description: A simple, but generic state machine framework for Dart.
environment:
  sdk: ^1.8.0
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0
