name: statemachine
version: 0.0.4+m4
author: Lukas Renggli <renggli@gmail.com>
description: A simple, but generic state machine framework for Dart.
homepage: https://github.com/renggli/StateMachineDart
dev_dependencies:
  junitconfiguration: '>=0.4.4'
  unittest: '>=0.4.4'
  browser: '>=0.4.4'
