name: statemachine
version: 0.0.1
author: Lukas Renggli <renggli@gmail.com>
description: A simple, but generic state machine framework for Dart.
homepage: https://github.com/renggli/StateMachineDart
dependencies:
  junitconfiguration: any
  unittest: '>=0.3.1+1'
  browser: '>=0.3.1+1'

#dependencies:
#  js: any
#  unittest: any